name       : snes9x-gtk
version    : '1.54'
release    : 4
homepage   : http://www.snes9x.com
source     :
    - https://github.com/snes9xgit/snes9x/archive/1.54.tar.gz : aa119763ca89a91c5f9f20379d013d014b58dcdd7014080bccf1f1fc8f0dfa4e
license    :
    - GPL-2.0
    - LGPL-2.1
component  : games.emulator
summary    : Snes9x - Portable Super Nintendo Entertainment System (TM) emulator
description: |
    Snes9x - Portable Super Nintendo Entertainment System (TM) emulator.
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(libxml-2.0)
    - pkgconfig(sdl2)
    - pkgconfig(SDL2_image)
    - pkgconfig(xv)
    - gawk
    - intltool
clang      : no
setup      : |
    cd gtk
    ./autogen.sh
    ./configure --prefix=/usr --without-oss
build      : |
    %make -C gtk
install    : |
    install -dm644 %installroot%/usr/bin/
    install -Dm0755 gtk/snes9x-gtk %installroot%/usr/bin/snes9x-gtk
    install -Dm644 $pkgfiles/snes9x.png $installdir/usr/share/pixmaps/snes9x.png
    install -Dm644 $pkgfiles/snes9x-gtk.desktop $installdir/usr/share/applications/snes9x-gtk.desktop
