name       : snes9x-gtk
version    : 1.54.1
release    : 7
homepage   : http://www.snes9x.com
source     :
    - https://github.com/snes9xgit/snes9x/archive/1.54.1.tar.gz : 85862a22498bc418c37bd7c81a3089d9cc00af279b91e5f7fa8bea05e2e3027b
license    :
    - GPL-2.0
    - LGPL-2.1
component  : games.emulator
summary    : Snes9x - Portable Super Nintendo Entertainment System (TM) emulator
description: |
    Snes9x - Portable Super Nintendo Entertainment System (TM) emulator.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(libxml-2.0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl)
    - pkgconfig(SDL_image)
    - pkgconfig(xrandr)
    - pkgconfig(xv)
    - gawk
    - intltool
clang      : no
setup      : |
    cd gtk
    ./autogen.sh
    ./configure --prefix=/usr --without-oss
build      : |
    %make -C gtk
install    : |
    install -dm644 %installroot%/usr/bin/
    install -Dm0755 gtk/snes9x-gtk %installroot%/usr/bin/snes9x-gtk
    install -Dm644 $pkgfiles/snes9x.png $installdir/usr/share/pixmaps/snes9x.png
    install -Dm644 $pkgfiles/snes9x-gtk.desktop $installdir/usr/share/applications/snes9x-gtk.desktop
