name       : snes9x-gtk
version    : 1.56.2
release    : 11
homepage   : http://www.snes9x.com
source     :
    - https://github.com/snes9xgit/snes9x/archive/1.56.2.tar.gz : 1557ade36c3b47aedf766b4504d141521f565664a6264c04f4c44f5a2dfada4f
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : games.emulator
summary    : Snes9x - Portable Super Nintendo Entertainment System (TM) emulator
description: |
    Snes9x is a portable, freeware Super Nintendo Entertainment System (SNES) emulator. It basically allows you to play most games designed for the SNES and Super Famicom Nintendo game systems on your PC or Workstation; which includes some real gems that were only ever released in Japan.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(libxml-2.0)
    - pkgconfig(minizip)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sdl2)
    - pkgconfig(xrandr)
    - pkgconfig(xv)
    - gawk
    - intltool
    - libepoxy
setup      : |
    cd gtk
    ./autogen.sh
    ./configure --prefix=/usr --without-oss
build      : |
    %make -C gtk
install    : |
    install -dm00644 %installroot%/usr/bin/
    install -Dm00755 gtk/snes9x-gtk %installroot%/usr/bin/snes9x-gtk
    install -Dm00644 $pkgfiles/snes9x.png $installdir/usr/share/pixmaps/snes9x.png
    install -Dm00644 $pkgfiles/snes9x-gtk.desktop $installdir/usr/share/applications/snes9x-gtk.desktop
