name       : snes9x-gtk
version    : 1.53
release    : 1
homepage   : http://www.snes9x.com
source     :
    - https://github.com/snes9xgit/snes9x/archive/1.53.tar.gz : b27cc34f03334a9316881d1597c97c78c472561cd8399483c3841eaf938c9ab3
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Snes9x - Portable Super Nintendo Entertainment System (TM) emulator 
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(sdl2)
    - pkgconfig(xv)
    - intltool
    - pkgconfig(glib-2.0)
    - pkgconfig(libxml-2.0)
    - gawk
    - pkgconfig(SDL2_image) 
    - pkgconfig(libpulse)
description: |
    Snes9x - Portable Super Nintendo Entertainment System (TM) emulator.
clang      : no
setup      : |
    cd gtk
    ./autogen.sh
    ./configure --prefix=/usr --without-oss
build      : |
    %make -C gtk
install    : |
    mkdir -p $installdir/usr/bin
    mkdir -p $installdir/usr/share/applications
    mkdir -p $installdir/usr/share/pixmaps/
    cp gtk/snes9x-gtk $installdir/usr/bin/
    chown root:root $installdir/usr/bin/snes9x-gtk
    install $pkgfiles/snes9x.png $installdir/usr/share/pixmaps/
    install $pkgfiles/snes9x-gtk.desktop $installdir/usr/share/applications/
